version: '3.7'

services:
  main:
    container_name: service.user
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${MICROSERVICE_PORT}:${MICROSERVICE_PORT}
      - 9229:9229
    command: >
      sh -c "npm run start:debug"
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongodb
  mongodb:
    container_name: service.user.mongodb
    image: mongo
    networks:
      - webnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
networks:
  webnet:
volumes:
  mongodata:
